name: "Check if NuGet version is published"
description: "Checks if the given package version is already published on AT.Public.NuGet."

inputs:
  name:
    description: "The package name"
    required: true
  version:
    description: "The package version"
    required: true

outputs:
  published:
    description: "true if the version is already published, false otherwise"
    value: ${{ steps.nuget_version_check.outputs.published }}
  last_version:
    description: "The last version published"
    value: ${{ steps.nuget_version_check.outputs.last_version }}
runs:
  using: "composite"
  steps:
    - uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4
      with:
        dotnet-version: "8.0.x"
    - name: Check if version is already published on NuGet
      id: nuget_version_check
      shell: bash
      run: |
        NAME="${{ inputs.name }}"
        VERSION="${{ inputs.version }}"
        SEARCH=$(dotnet package search "$NAME" --prerelease --format json)
        echo "$SEARCH"
        FOUND=$(echo "$SEARCH" | jq '.searchResult[] | select(.sourceName=="AT.Public.NuGet")' | jq --arg VERSION "$VERSION" '.packages[] | select(.latestVersion == $VERSION) | .latestVersion' | tr -d '"')
        LAST_VERSION=$(echo "$SEARCH" | jq '.searchResult[] | select(.sourceName=="AT.Public.NuGet")' | jq '.packages[] | .latestVersion' | tr -d '"' | head -n 1)
        echo "last_version=$LAST_VERSION" >> $GITHUB_OUTPUT
        if [ "$FOUND" = "$VERSION" ]; then
          echo "The version ($FOUND) for $NAME is already published in the AT.Public.NuGet feed."
          echo "published=true" >> $GITHUB_OUTPUT
        else
          echo "Last version published for $NAME in the AT.Public.NuGet feed was '$LAST_VERSION'. The given version $VERSION is not the same."
          echo "published=false" >> $GITHUB_OUTPUT
        fi
