<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Arbeidstilsynet.Common.TestExtensions.Snapshots.Pdf.Test</RootNamespace>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <IsTestProject>true</IsTestProject>
    <TestingPlatformCommandLineArguments>$(TestingPlatformCommandLineArguments) --ignore-exit-code 8</TestingPlatformCommandLineArguments>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Shouldly" Version="4.3.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="xunit.v3.mtp-v2" Version="4.0.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.11.2" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Fonts\NotoSans-Regular.ttf" LogicalName="NotoSans-Regular.ttf" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AT.Common.TestExtensions.Snapshots.Pdf.Publish\AT.Common.TestExtensions.Snapshots.Pdf.Publish.csproj" />
  </ItemGroup>
</Project>
