namespace Arbeidstilsynet.Common.AltinnApp.Abstract.Processing;

/// <summary>
/// Processes changes in a list of items within a data model.
/// </summary>
/// <typeparam name="TDataModel"></typeparam>
/// <typeparam name="TListItem"></typeparam>
public abstract class ListProcessor<TDataModel, TListItem>
    : MemberProcessor<TDataModel, List<TListItem>>
    where TDataModel : class
{
    /// <inheritdoc />
    protected ListProcessor()
    {
        if (
            typeof(TListItem).GetProperty(Extensions.AltinnRowIdPropertyName)
                is not { } propertyInfo
            || propertyInfo.PropertyType != typeof(Guid)
        )
        {
            throw new InvalidOperationException(
                $"Type {typeof(TListItem).Name} must have a property named {Extensions.AltinnRowIdPropertyName} of type Guid. This should be auto-generated by Altinn for types used in repeating groups in the data model."
            );
        }
    }

    /// <inheritdoc />
    protected sealed override async Task ProcessMember(
        List<TListItem>? currentList,
        List<TListItem>? previousList,
        TDataModel currentDataModel,
        TDataModel previousDataModel
    )
    {
        var prevItems =
            previousList?.ToDictionary(item => item.GetAltinnRowId(), item => item) ?? [];
        var currItems =
            currentList?.ToDictionary(item => item.GetAltinnRowId(), item => item) ?? [];

        foreach (var rowId in currItems.Keys.Union(prevItems.Keys))
        {
            var currentItem = currItems.GetValueOrDefault(rowId);
            var previousItem = prevItems.GetValueOrDefault(rowId);
            if (currentItem is null && previousItem is null)
            {
                continue; // Both items are null, nothing to process
            }

            if (currentItem is null || previousItem is null)
            {
                // One of the items is null, treat it as a change
                await ProcessItem(currentItem, previousItem, currentDataModel, previousDataModel);
            }
            else if (!currentItem.Equals(previousItem))
            {
                // If the items are not equal, process the change
                await ProcessItem(currentItem, previousItem, currentDataModel, previousDataModel);
            }
        }
    }

    /// <summary>
    /// Called for each list item that has changed (based on !currentItem.Equals(previousItem)). Current and previous share the same AltinnRowId.
    /// </summary>
    /// <param name="currentItem">When this is null, the item was just deleted</param>
    /// <param name="previousItem">When this is null, the item was just added</param>
    /// <param name="currentDataModel"></param>
    /// <param name="previousDataModel"></param>
    /// <returns></returns>
    protected virtual Task ProcessItem(
        TListItem? currentItem,
        TListItem? previousItem,
        TDataModel currentDataModel,
        TDataModel previousDataModel
    ) => Task.CompletedTask;
}

file static class Extensions
{
    public const string AltinnRowIdPropertyName = "AltinnRowId";

    public static Guid GetAltinnRowId<TListItem>(this TListItem item)
    {
        var propertyInfo = typeof(TListItem).GetProperty(AltinnRowIdPropertyName);
        if (propertyInfo is null || propertyInfo.PropertyType != typeof(Guid))
        {
            throw new InvalidOperationException(
                $"Type {typeof(TListItem).Name} must have a property named '{AltinnRowIdPropertyName}' of type Guid."
            );
        }

        var value = (Guid?)propertyInfo.GetValue(item);

        if (value == null)
        {
            throw new InvalidOperationException(
                $"The '{AltinnRowIdPropertyName}' property of item of type {typeof(TListItem).Name} cannot be null."
            );
        }

        return value.Value;
    }
}
