name: "Publish .NET NuGet Package"
description: "Packs and publishes a .NET package to NuGet if not already published"

inputs:
  package-path:
    description: "The directory containing the .csproj to publish"
    required: true
  name:
    description: "The package name"
    required: true
  version:
    description: "The package version"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4
      with:
        dotnet-version: "8.0.x"
        source-url: https://pkgs.dev.azure.com/Atil-utvikling/Public/_packaging/AT.Public.NuGet/nuget/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.AZURE_DEVOPS_PUBLISH_PACKAGE_PAT}}

    - name: Pack and publish NuGet package
      shell: bash
      working-directory: ${{ inputs.package-path }}
      run: |
        echo "Packing ${{ inputs.name }} version ${{ inputs.version }}"
        dotnet pack -c Release
        dotnet nuget push "./bin/Release/*.nupkg" -k GithubDeployJob
        echo "Published ${{ inputs.name }} version ${{ inputs.version }}"
