on:
  workflow_call:
    inputs:
      package-path:
        required: true
        type: string

jobs:
  check-and-prepare:
    runs-on: ubuntu-latest
    outputs:
      should-continue: ${{ steps.check_changes.outputs.should-continue }}
      parent_dir: ${{ steps.get_parent_dir.outputs.parent_dir }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if changes are inside package path
        id: check_changes
        run: |
          rel_path="${{ inputs.package-path }}"
          rel_path="${rel_path#./}"
          if git diff --name-only origin/main...HEAD | grep -q "$rel_path"; then
            echo "should-continue=true" >> $GITHUB_OUTPUT
          else
            echo "should-continue=false" >> $GITHUB_OUTPUT
          fi

      - uses: actions/setup-dotnet@v4
        if: steps.check_changes.outputs.should-continue == 'true'
        with:
          dotnet-version: '8.0.x'
          config-file: ./nuget.config

      - name: Get parent directory
        id: get_parent_dir
        run: |
          rel_path="${{ inputs.package-path }}"
          rel_path="${rel_path#./}"
          echo "DEBUG: rel_path=$rel_path"
          parent_dir=$(dirname "$rel_path")
          echo "DEBUG: parent_dir=$parent_dir"
          echo "parent_dir=$parent_dir" >> $GITHUB_OUTPUT

  build-dotnet:
    needs: check-and-prepare
    if: needs.check-and-prepare.outputs.should-continue == 'true'
    uses: ./.github/workflows/dotnet-build-template.yaml
    with:
      working-directory: ${{ needs.check-and-prepare.outputs.parent_dir }}






